export const GET_MENU_ITEMS = 'GET_MENU_ITEMS';
export const GET_COLLECTION = 'GET_COLLECTION';

export const SET_CHART_VALUE = 'GET_CHART_VALUE';
export const RESET_CHART = 'RESET_CHART';
export const RESET_FOUND = 'RESET_FOUND';
export const CHART_QUANTITY_INCREMENT = 'CHART_QUANTITY_INCREMENT';
export const CHART_QUANTITY_DECREMENT = 'CHART_QUANTITY_DECREMENT';

export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM';

export const GET_ITEM_DETAILS = 'GET_ITEM_DETAILS';
export const DETAILS_QUANTITY_INCREMENT = 'DETAILS_QUANTITY_INCREMENT';
export const DETAILS_QUANTITY_DECREMENT = 'DETAILS_QUANTITY_DECREMENT';

export const SIGNIN_EMAIL = 'SIGNIN_EMAIL';
export const SIGNIN_PASSWORD = 'SIGNIN_PASSWORD';

export const GET_AUTH_USER = 'GET_AUTH_USER';